### ISSUE TITLE
Remove reexports

### ISSUE THREAD

**Issue by cscherrer** [AnderGray/TransitionalMCMC.jl#3]
Hi, this package looks really nice! I did notice that there are currently these lines:
```julia
@reexport using Distributed
@reexport using StatsBase
@reexport using Distributions
```

With the setup, `using TransitionalMCMC` will currently clutter the namespace with lots of unrelated things. It's not such a big deal, but will lead to many people using it through `import` instead.  That's especially the case for me, since I'm mostly using MeasureTheory in place of Distributions (with the latter only to fill in some current gaps).

It's easy enough for users to call `using` if they want. Could these be removed?

**Comment by AnderGray** [comment]
Hey, thanks for your interest and you comment.

For sure this is a good idea. 
Cheers!

**Comment by AnderGray** [comment]
Fixed with this [commit](https://github.com/AnderGray/TransitionalMCMC.jl/commit/bd9f06d9f28798e7b6cb993e532c80fc489ef762)
